### ISSUE TITLE
null.gif and file.gif throw 404 errors

### ISSUE THREAD

**Issue by jimafisk** [nullitics/nullitics#7]
The docs for tracking users with disabled JS (https://nullitics.com/docs/#/script?id=disabled-javascript) use this URL: https://nullitics.com/file.gif. That gives me a 404 error, is this intentional? Thanks!

**Comment by jimafisk** [comment]
I see that https://nullitics.com/script.js references https://nullitics.com/null.gif which also throws 404. This is probably just how things are supposed to work, but I'm curious if there's a way around this so it doesn't put errors in the browser console.

**Comment by zserge** [comment]
Exactly, 404 is returned to stop bots and crawlers, as long as the request parameters are missing or invalid. This is the expected behaviour:

* Tracking pixel itself, with no query parameters and no Referer headers would result in 404 (there is not enough information to handle this request, and 404 is chosen vs other 4xx status codes to stop the bots from trying)
* Tracking pixel with Referer header would result in 200 OK
* Tracking pixel with no Referer header but with `?u=` query parameter with a valid website URL would also result in 200 OK.
